// MealCard — renders the AI-generated meal plan beautifully
// Props:
//   mealPlan: string — the raw AI response text
//   onCopy: function — called when user copies the plan
//   onRegenerate: function — called when user clicks regenerate
//   isRegenerating: boolean — shows spinner on regenerate button

import { useState } from 'react'

export default function MealCard({ mealPlan, onCopy, onRegenerate, isRegenerating }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(mealPlan)
      setCopied(true)
      onCopy?.()
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback for older browsers
      const el = document.createElement('textarea')
      el.value = mealPlan
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    }
  }

  // Render plain text with basic markdown-like formatting for bolding day names
  const renderContent = (text) => {
    return text.split('\n').map((line, i) => {
      // Bold **text**
      const formatted = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      // Day headers (Monday, Tuesday, etc.)
      if (/^[*#]?\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)/i.test(line)) {
        return (
          <div key={i} className="mt-5 first:mt-0">
            <div
              className="inline-flex items-center gap-2 px-3 py-1 bg-rose-50 dark:bg-rose-900/30 rounded-lg mb-2"
              dangerouslySetInnerHTML={{ __html: `<span class="text-rose-500 font-bold text-sm">${formatted.replace(/^[*#\s]+/, '')}</span>` }}
            />
          </div>
        )
      }
      // Meal lines (Breakfast, Lunch, Dinner)
      if (/^[-•*]\s*(🌅|🥗|🍽️|Breakfast|Lunch|Dinner)/i.test(line)) {
        return (
          <p
            key={i}
            className="text-sm text-gray-600 dark:text-gray-300 py-1 pl-2 border-l-2 border-rose-100 dark:border-rose-900/50 ml-1"
            dangerouslySetInnerHTML={{ __html: formatted.replace(/^[-•*]\s*/, '') }}
          />
        )
      }
      // Empty lines
      if (!line.trim()) return <div key={i} className="h-1" />
      // Default paragraph
      return (
        <p
          key={i}
          className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: formatted }}
        />
      )
    })
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-card border border-rose-50 dark:border-gray-700 overflow-hidden animate-slideUp">
      {/* Card header */}
      <div className="px-6 py-4 bg-gradient-to-r from-rose-50 to-lavender-50 dark:from-rose-900/20 dark:to-purple-900/20 border-b border-rose-100 dark:border-gray-700">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-xl">🍽️</span>
            <div>
              <h3 className="font-bold text-gray-800 dark:text-white text-sm">Your 5-Day Meal Plan</h3>
              <p className="text-xs text-gray-400">Generated by Aime ✨</p>
            </div>
          </div>
          {/* Action buttons */}
          <div className="flex items-center gap-2">
            <button
              id="copy-meal-plan"
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all
                ${copied
                  ? 'bg-green-500 text-white'
                  : 'bg-white dark:bg-gray-700 text-gray-600 dark:text-gray-400 border border-gray-200 dark:border-gray-600 hover:border-rose-300 hover:text-rose-500'
                }`}
            >
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
            <button
              id="regenerate-meal-plan"
              onClick={onRegenerate}
              disabled={isRegenerating}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-rose-500 text-white hover:bg-rose-600 disabled:opacity-60 transition-all"
            >
              {isRegenerating ? (
                <>
                  <span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Generating...
                </>
              ) : (
                <>🔄 Regenerate</>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Meal plan content */}
      <div className="px-6 py-5 space-y-1 max-h-[500px] overflow-y-auto">
        {renderContent(mealPlan)}
      </div>
    </div>
  )
}
